scenario: rcp85
domain: engwales
ensemble_members:
- '01'
# - '04'
# - '05'
# - '06'
# - '07'
# - '08'
# - '09'
# - '10'
# - '11'
# - '12'
# - '13'
# - '15'
predictands:
  frequency: 1hr
  resolution: 2.2km-coarsened-4x
  collection: land-cpm
  variables:
    - pr
predictors:
  frequency: day
  resolution: 2.2km-coarsened-gcm
  collection: land-cpm
  variables:
      - psl
      - spechum250
      - spechum500
      - spechum700
      - spechum850
      - temp250
      - temp500
      - temp700
      - temp850
      - vorticity250
      - vorticity500
      - vorticity700
      - vorticity850
split:
  scheme: random
  seed: 42
  props:
    train: 0.7
    val: 0.15
    test: 0.15
