variable: pr
attrs:
  units: kg m-2 s-1
  standard_name: precipitation_flux
  grid_mapping: latitude_longitude
sources:
  type: moose
  collection: land-gcm
  frequency: day
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: pr
spec:
  - action: shift_lon_break
  - action: select-subdomain
    parameters:
      domain: ${domain}
  # implicit final actions: assign attrs
