variable: temp${theta}
attrs:
  units: K
  standard_name: air_temperaturehPa
  grid_mapping: rotated_latitude_longitude
sources:
  type: moose
  collection: land-gcm
  frequency: day
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: temp{theta}
spec:
  - action: shift_lon_break
  - action: select-subdomain
    parameters:
      domain: ${domain}
      size: ${size}
  # implicit final actions: assign attrs, save, cleanup extraction?
